apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
  namespace: todoapp
  labels:
    app: todoapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: ikulyk404/todoapp:3.0.0
        ports:
        - containerPort: 8080

        env:
        - name: EXTERNAL_ENDPOINT
          value: "http://httpbin-api.mateapp.svc.cluster.local"

        - name: PYTHONUNBUFFERED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONUNBUFFERED
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: SECRET_KEY

        volumeMounts:
        - name: storage-volume
          mountPath: /app/data
        - name: config-volume
          mountPath: /app/configs
          readOnly: true
        - name: secret-volume
          mountPath: /app/secrets
          readOnly: true

        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        livenessProbe:
          httpGet:
            path: api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: api/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

      volumes:
      - name: storage-volume
        persistentVolumeClaim:
          claimName: todoapp-pvc
      - name: config-volume
        configMap:
          name: app-config
      - name: secret-volume
        secret:
          secretName: app-secret